name: Logger workflow

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn

      - name: build
        run: |
          yarn build

      - name: deploy
        run: |
          npm i -g pm2
          pm2 start dist/main.js --name logger
