name: Logger workflow

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          yarn

      - name: build
        run: |
          yarn build

      - name: deploy
        run: |
          pm2 start dist/main.js --name logger
