name: Logger workflow

on:
  push:
    branches:
      - develop
      - main

  workflow_dispatch:

jobs:
  build:
    name: build & deploy
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          /home/asaje/.nvm/versions/node/v18.14.2/bin/yarn 

      - name: build
        run: |
          /home/asaje/.nvm/versions/node/v18.14.2/bin/yarn build

      - name: deploy
        run: |
          /home/asaje/.nvm/versions/node/v18.14.2/bin/pm2 start dist/main.js --name logger
